# Generated by Django 5.2.7 on 2025-11-03 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='productModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productTitle', models.CharField(max_length=230)),
                ('productDescription', models.TextField(max_length=600)),
                ('productPrice', models.IntegerField()),
                ('productStock', models.IntegerField()),
                ('productImage', models.ImageField(upload_to='productImages/')),
                ('productCategory', models.PositiveSmallIntegerField(choices=[(0, 'Analgesics'), (1, 'Antibiotics'), (2, 'Antihistamines'), (3, 'Antihistamines')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='cartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateField(auto_now=True)),
                ('cartCategory', models.PositiveSmallIntegerField(choices=[(0, 'Placed'), (1, 'Dispatched'), (2, 'Shipped'), (3, 'Delivered')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminPortal.productmodel')),
            ],
        ),
    ]
