# Generated by Django 5.2.7 on 2025-11-11 23:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='paymentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentType', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='cartCategory',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='productImage',
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='cartStatus',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Unplaced'), (0, 'Placed'), (1, 'Dispatched'), (2, 'Shipped'), (3, 'Delivered'), (4, 'Canceled')], default=5),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='productQuantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='productCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminPortal.categories'),
        ),
        migrations.CreateModel(
            name='productImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productImage', models.ImageField(upload_to='productImages/')),
                ('isDeleted', models.BooleanField(default=False)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminPortal.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='productManagementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('price', models.BigIntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminPortal.cartmodel')),
            ],
        ),
    ]
