# Generated by Django 5.2.7 on 2025-11-03 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0002_remove_productmodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='productImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productImage', models.ImageField(upload_to='productImages/')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminPortal.productmodel')),
            ],
        ),
    ]
