# Generated by Django 5.2.7 on 2025-11-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0002_categories_paymentmethods_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
