# Generated by Django 5.2.7 on 2025-11-03 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0003_productimagemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='productImage',
        ),
    ]
