# Generated by Django 5.2.7 on 2025-11-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0004_alter_categories_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='productQuantity',
            field=models.IntegerField(),
        ),
    ]
