# Generated by Django 5.2.7 on 2025-11-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0005_productimagemodel_user_productmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimagemodel',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
