# Generated by Django 5.2.7 on 2025-11-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0005_alter_cartmodel_productquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='productQuantity',
            field=models.IntegerField(default=0),
        ),
    ]
