# Generated by Django 5.2.7 on 2025-11-04 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0006_productimagemodel_isdeleted_productmodel_isdeleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimagemodel',
            name='user',
        ),
    ]
