# Generated by Django 5.2.7 on 2025-11-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0006_alter_cartmodel_productquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='cartStatus',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Unplaced'), (0, 'Placed'), (1, 'Dispatched'), (2, 'Shipped'), (3, 'Delivered'), (4, 'Cancelled')], default=5),
        ),
    ]
