# Generated by Django 5.2.7 on 2025-11-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0007_remove_productimagemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='productCategory',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Analgesics'), (1, 'Antibiotics'), (2, 'Antifungals'), (3, 'Antihistamines')], default=0),
        ),
    ]
