# Generated by Django 5.2.7 on 2025-11-06 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0008_alter_productmodel_productcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='cartCategory',
            new_name='cartStatus',
        ),
    ]
