# Generated by Django 5.2.7 on 2025-11-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0009_rename_cartcategory_cartmodel_cartstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='productQuantity',
            field=models.IntegerField(default=1),
        ),
    ]
