# Generated by Django 5.2.7 on 2025-11-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0010_cartmodel_productquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
