# Generated by Django 5.2.7 on 2025-11-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0012_productmanagementmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
