# Generated by Django 5.2.7 on 2025-11-07 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0013_cartmodel_purchased'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmanagementmodel',
            name='user',
        ),
    ]
