# Generated by Django 5.2.7 on 2025-11-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0014_remove_productmanagementmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmanagementmodel',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
    ]
