# Generated by Django 5.2.7 on 2025-11-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0015_productmanagementmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='cartStatus',
            field=models.PositiveSmallIntegerField(choices=[(0, 'UnPlaced'), (1, 'Placed'), (2, 'Dispatched'), (3, 'Shipped'), (4, 'Delivered')], default=0),
        ),
    ]
