# Generated by Django 5.2.7 on 2025-11-08 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0017_productmanagementmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmanagementmodel',
            name='user',
        ),
    ]
