# Generated by Django 5.2.7 on 2025-11-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0020_alter_cartmodel_cartstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='cartStatus',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Placed'), (1, 'Dispatched'), (2, 'Shipped'), (3, 'Delivered')]),
        ),
    ]
