# Generated by Django 5.2.7 on 2025-11-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0021_alter_cartmodel_cartstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmanagementmodel',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='cartStatus',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Unplaced'), (0, 'Placed'), (1, 'Dispatched'), (2, 'Shipped'), (3, 'Delivered')], default=5),
        ),
    ]
