# Generated by Django 5.2.7 on 2025-11-10 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0025_alter_productmanagementmodel_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
