# Generated by Django 5.2.7 on 2025-11-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0026_delete_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='cartStatus',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Unplaced'), (0, 'Placed'), (1, 'Dispatched'), (2, 'Shipped'), (3, 'Delivered'), (4, 'Canceled')], default=5),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='productCategory',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Analgesics'), (1, 'Antibiotics'), (2, 'Antifungals'), (3, 'Antihistamines')]),
        ),
    ]
