# Generated by Django 5.2.7 on 2025-11-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0027_alter_cartmodel_cartstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentType', models.CharField(max_length=15)),
            ],
        ),
    ]
