# Generated by Django 5.2.7 on 2025-11-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0028_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='paymentType',
            field=models.CharField(max_length=30),
        ),
    ]
