# Generated by Django 5.2.7 on 2025-11-11 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0029_alter_paymentmethod_paymenttype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='paymentMethod',
        ),
    ]
