# Generated by Django 5.2.7 on 2025-11-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0030_delete_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentType', models.CharField(max_length=30)),
            ],
        ),
    ]
