# Generated by Django 5.2.7 on 2025-11-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'MALE'), (1, 'FEMALE'), (2, 'OTHER')], default=0),
            preserve_default=False,
        ),
    ]
