# Generated by Django 5.2.7 on 2025-11-02 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_customuser_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_no',
            new_name='phoneNo',
        ),
    ]
