# Generated by Django 5.2.7 on 2025-11-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0004_alter_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profilePhoto',
            field=models.ImageField(default=None, upload_to='profileImage/'),
            preserve_default=False,
        ),
    ]
