# Generated by Django 5.2.7 on 2025-11-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0005_customuser_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profilePhoto',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
