# Generated by Django 5.2.7 on 2025-11-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0007_userimagemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profilePhoto',
        ),
        migrations.RemoveField(
            model_name='userimagemodel',
            name='productImage',
        ),
        migrations.AddField(
            model_name='userimagemodel',
            name='profilePhoto',
            field=models.ImageField(default=None, upload_to='media/'),
            preserve_default=False,
        ),
    ]
