# Generated by Django 5.2.7 on 2025-11-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0008_remove_customuser_profilephoto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimagemodel',
            name='profilePhoto',
            field=models.ImageField(upload_to='profilePhoto/'),
        ),
    ]
